#index:
#    path: /
#    controller: App\Controller\DefaultController::index

items:
  type:     rest
  resource: App\Controller\ItemController

fidelity:
  type:     rest
  resource: App\Controller\FidelityController