items:
  type:     rest
  resource: App\Controller\ItemController

fidelity:
  type:     rest
  resource: App\Controller\FidelityController

default:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: 'https://www.supergabry.it'
    permanent: true
    keepQueryParams: true